# Generated by Django 3.0.7 on 2020-10-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=512)),
                ('to', models.TextField(blank=True, null=True)),
                ('cc', models.TextField(blank=True, null=True)),
                ('bcc', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=1024, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(db_index=True, default=False)),
                ('sent_on', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('send_successful', models.BooleanField(default=False)),
                ('fail_message', models.CharField(blank=True, max_length=256, null=True)),
                ('email_class', models.CharField(max_length=256)),
                ('email_dump', models.TextField()),
            ],
        ),
    ]
