# Generated by Django 2.0 on 2020-10-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='timestamp',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='email_class',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='email_dump',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='fail_message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='send_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='sent_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='from_email',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
