# Generated by Django 5.2.2 on 2025-08-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_auto_20210118_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='email_dump_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
