# Generated by Django 4.2.8 on 2024-01-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email", "0002_auto_20210118_1109"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="blocked_addresses",
            field=models.TextField(blank=True, null=True),
        ),
    ]
