# Generated by Django 5.2.6 on 2025-09-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0003_emailmessage_email_dump_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='send_successful',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
