# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-16 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0005_auto_20190215_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
