#!/usr/bin/python3
import sys
import subprocess

tags = subprocess.run("git for-each-ref --sort=-creatordate --format '%(objectname) %(refname:strip=2)' refs/tags", shell=True, capture_output=True, text=True)
tags = tags.stdout.split('\n')
tags = (tag.split(' ', 1) for tag in tags)
tags = [tag for tag in tags if len(tag) == 2]

if '--norc' in sys.argv:
    tags = [tag for tag in tags if 'rc' not in tag[1]]

if tags:
    print(tags[0][0])
