#!/bin/bash
git fetch --all --tags --quiet
LATEST_COMMIT_TAG=`git_latest_tag --norc`
LATEST_TAG=`git describe --tags $LATEST_COMMIT_TAG`
echo Checking out latest tag: $LATEST_TAG
git checkout --quiet $LATEST_TAG
git submodule update --recursive
